#!/usr/bin/env bash
# Dependencies | wireless_tools |
#
get_NIC="$(ip link | awk '/state UP/ {print $2}')"

# Check if we have installed "wireless_tools"

if command -v iwgetid >/dev/null 2>&1 ;then
  SSID="$(iwgetid -r)"
fi

net_stat () {
  if (ping -c 1 archlinux.org || ping -c 1 gnu.org) &>/dev/null; then
    if [[ $get_NIC == e* ]]; then
      echo "Online"
      echo "󰈀"
    else
      echo "$SSID"
      echo ""
    fi
  else
    echo "Offline"
    echo "󱚵"
  fi
}

case "$1" in
  --stat)
    net_stat | head -n1;;
  --icon)
    net_stat | tail -n1;;
esac


