#!/usr/bin/env bash

# @requires: pactl

SINK=$(pactl list short sinks | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,' | head -n 1)


get_percentage () {
  local muted=$(pamixer --get-volume-human)
  if [[ $muted == 'muted' ]]; then
    echo "0"
  else
    per=$(pamixer --get-volume)
    echo "${per}"
  fi
}

get_icon () {
  local vol=$(get_percentage)
  if [[ $vol == "0" ]]; then
    echo "󰸈 |"
  else
    echo "󰕾 |"
  fi
}

get_vol () {
  local percent=$(get_percentage)
  echo "$percent" | tr -d '%'
}

get_INC () {
    pactl set-sink-volume $SINK +2%
    dunstify -u low -i $HOME/.config/bspwm/notifyIcons/SIncrease.png "Volume Up" "$(get_percentage)%"
}

get_DEC () {
    pactl set-sink-volume $SINK -2%
    dunstify -u low -i $HOME/.config/bspwm/notifyIcons/SReduce.png "Volume Down" "$(get_percentage)%"
}
if command -v pulseaudio &>/dev/null; then

    case "$1" in
        --icon)
            get_icon
            ;;
        --percentage)
            get_percentage
            ;;
        --vol)
            get_vol
            ;;
        --toggle)
            if [[ "$(get_percentage)" != 0 ]]; then
                dunstify -u low -i $HOME/.config/bspwm/notifyIcons/SMuted.png "Muted" "Silence 🤫"
            else
                dunstify -u low -i $HOME/.config/bspwm/notifyIcons/SHigh.png "Volum High" "Noise on 🎶"
            fi 
            pactl set-sink-mute $SINK toggle
            ;;
        --inc)
            get_INC 
            ;;
        --dec)
            get_DEC 
            ;;
        --set)
            val=$(echo $2 | tr '.' ' ' | awk '{print $1}')
            if test $val -gt 100; then
                val=100
            fi
            pactl set-sink-volume $SINK $val%
            ;;
    esac
else
    dunstify -u critical -i $HOME/.config/bspwm/notifyIcons/nofound.png "Pulseaudio No Found" "Driver no found, requires pulseaudio"
fi
