#!/bin/sh 

# zbaylin
# Mod by 0xMsDos


#########################################
#                   VARS                #
#########################################

FIELDS=SSID,SECURITY,BARS

# List of available networks
LIST=$(nmcli --fields "$FIELDS" device wifi list | grep -v "ESSID")
# Anchor
RWIDTH=$(($(echo "$LIST" | head -n1 | awk '{print length($0); }')+2))
# Total rows
LINENUM=$(echo "$LIST" | wc -l)
# Known connections
KNOWCON=$(nmcli connection show)

CONSTATE=$(nmcli -fields WIFI g)

CURRSSID=$(LANGUAGE=c nmcli -t -f active,ssid dev wifi | awk -F: '$1 ~ /^yes/ {print $2}')

# If the variable is not empty
if [[ ! -z $CURRSSID ]]; then
  HIGHLINE=$(echo "$(echo "$LIST" | awk -F "[ ]{2,}" '{print $1}' | grep -Fxn -m 1 "$CURRSSID" | awk -F ":" '{print $1}') +1" | bc)
fi
  

if [ "$LINENUM" -gt 8 ] && [[ "$CONSTATE" =~ "enabled" ]]; then
  LINENUM=8
elif [[ "$CONSTATE" =~ "disabled" ]]; then
  LINENUM=1
fi

if [[ "$CONSTATE" =~ "enabled" ]]; then
  TOGGLE="toggle off"
elif [[ "$CONSTATE" =~ "disabled" ]]; then
  TOGGLE="toggle on"
fi


CHENTRY=$(echo -e "$TOGGLE\nmanual\n$LIST" | uniq -u | rofi -dmenu -p "Search Wi-Fi SSID: " -lines "$LINENUM" -a "$HIGHLINE" -theme $HOME/.config/bspwm/rice/moran/wifiL.rasi -width -"$RWIDTH")

# Level the output (Nivelar la salida)

CHSSID=$(echo "$CHENTRY" | sed 's/\s\{2,\}/\|/g' | awk -F "|" '{print $1}')

#echo "$CHSSID"

if [ "$CHENTRY" == "manual" ]; then
    manSSID=$(echo "Ingresa el SSID (SSID, password)" | rofi -dmenu -p "Manual connection: " -theme $HOME/.config/bspwm/rice/moran/wifiL.rasi -columns 1 -lines 1)
  MSSID=$(echo "$manSSID" | awk -F "," '{print $1}')
  MPASS=$(echo "$manSSID" | awk -F "," '{print $2}')
  # Si tenemos una una conexión guardada
  if [ "$MPASS" = "" ]; then
    nmcli dev wifi con "$MSSID"
  else 
    nmcli dev wifi con "$MSSID" password "$MPASS"
  fi
elif [ "$CHENTRY" = "toggle on" ]; then
  nmcli radio wifi on
elif [ "$CHENTRY" = "toggle off" ]; then
  nmcli radio wifi off
else 

  if [ "$CHSSID" == "*" ]; then
    CHSSID=$(echo "$CHENTRY" | sed 's/\s\{2,\}/\|/g' | awk -F "|" '{print $3}')
  fi
  
  if [[ $(echo "$KNOWCON" | grep "$CHSSID") = "$CHSSID" ]]; then
    nmcli con up "$CHSSID"
  else 
    if [[ "$CHENTRY" =~ "WPA2" ]] || [[ "$CHENTRY" =~ "WEP" ]]; then
      WIFIPASS=$(echo "Escribe tu contraseña" | rofi -dmenu -p "password: " -lines 1 -theme gruvbox-dark-hard -font "Hack Nerd Font Mono 8")

    fi 
    
    connect=$(nmcli dev wifi con "$CHSSID" password "$WIFIPASS")
    
    if [ $? -eq 0 ]; then
      echo "Successful Connection" | rofi -dmenu -p "STATUS: " -theme gruvbox-dark-hard
    fi
    

  fi 

fi




